### ISSUE TITLE
Tracking which admin made changes

### ISSUE THREAD

**Issue by bovee** [onecodex/chrononaut#1]
It's possible for an admin to `flask app/run.py shell` and make changes. The history records created are traceable to an admin because the records have a `user_id` of `None` (in `change_info`), but it might not be clear _which_ admin made the change.

It may be desirable to have `fetch_current_user` return an environment variable (and require the environment variable to be set) if there's no request or app content. For example, invoking the CLI would then entail `USER=roderick flask app/run.py shell`, but all history records would be tagged with `roderick`.

**Comment by boydgreenfield** [comment]
@bovee This is a good idea, but I think should be part of the extra change information hook we provide (now supported more easily in v0.1.1 via a Flask config variable). Opening an issue to track for our internal app and closing for this repo.
